React capstone project - Metrics webapp 🗺️
ritikarawat220/ReactCapstone-project---Metrics-webapp pull request #4
Opened 2023-04-25 09:34 UTC by ritikarawat220

2023-04-26 16:05 UTC, Felix45 requested changes
Hi @ritikarawat220 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif" width="375px" />

## Highlights :heavy_check_mark: 
- [x] Application works well :heavy_check_mark: 
- [x] Application has a filter :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Gitflow is used correctly :white_check_mark:     


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 16:05 UTC, Felix45 commented on src/components/Countriesdetail.js
> +      </div>
- [Required] Good job implementing the country details page, however, I think your design for the page varies slightly from the design provided on Behance for this project. The details list is missing the `zebra-stripped` styling that is present in the Behance design. Please see the screenshot below for more details on this.
- [Required] Please also consider using the color `#fff;` on the text just the way it is on Behance, not text should have the color `#000;`

## Behance design
![Screenshot from 2023-04-26 17-54-42](https://user-images.githubusercontent.com/16392046/234616798-fffbcd93-787a-4c0c-99e4-fdf287927ad2.png)

## Your design
![Screenshot from 2023-04-26 17-53-43](https://user-images.githubusercontent.com/16392046/234616956-423172e1-d186-498c-a0fc-31a2cc19b8b3.png)

2023-04-26 16:05 UTC, Felix45 commented on public/index.html
> +  </body>
- [ Required] I think it would be nice if the font in your App matches the `font-family` on the Behance design. In [Behance.net Design >> ](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) the `font-family` is either `Lato` on input controls or `gill sans`, for the body and titles, kindly rectify this. 

- [Required] I think it would be better if the text `color`, `font-weight`, and `text-transform` (use of uppercase) on your App matches the design on Behance, currently, the homepage of your App has text color `#000` which is not consistent with the design template, please rectify this.

## Behance font
![Screenshot from 2023-04-26 18-00-27](https://user-images.githubusercontent.com/16392046/234619097-d9ad5bf1-fe0f-4c91-821c-607d17151e4f.png)

## Behance Font color
![Screenshot from 2023-04-26 18-59-05](https://user-images.githubusercontent.com/16392046/234633613-48aa8468-3896-49b4-acbf-8fa104651f28.png)

## Your design
![Screenshot from 2023-04-26 19-00-25](https://user-images.githubusercontent.com/16392046/234634526-cebe2b85-9174-4147-a072-3db7762bf8e3.png)

2023-04-26 16:05 UTC, Felix45 commented on src/components/Countries.js
> +    </ul>
- [ Required ] On the homepage of the Behance design the items are listed even before the filter is set. I would like to suggest that you set a default `continent` on the page so that your app always has a list of countries instead of displaying `No continent selected` which makes the page look blank. Please see the screenshot below and rectify this.

## Behance design
<img src="https://user-images.githubusercontent.com/16392046/234624047-2b2dca90-f44e-4cda-9377-4ffedc6bf7ba.png" width="375px" />

## Your design
<img src="https://user-images.githubusercontent.com/16392046/234624398-fa76208c-ed1c-4203-a490-83056a72336c.png" width="375px" />

2023-04-26 16:05 UTC, Felix45 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [Required] I think it would be nice if you add a link to a video presenting the features of the project you built on the _readme file_ or the description of the _Pull Request_. According to the project requirements, the video should have a maximum length of 5 minutes and the content of the video should include:

  - a description of the project.
  - a demo of the project features.
  - you should also highlight some interesting piece of code or something you built that you are very proud of.

## Project requirements
![Screenshot from 2023-04-26 18-35-09](https://user-images.githubusercontent.com/16392046/234628034-c7c5a8d8-da7c-4018-a63d-9935ddd62933.png)

2023-04-27 11:01 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @ritikarawat220  
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
 :heavy_check_mark: Linters are passing.
:heavy_check_mark: You have a good code structure.
:heavy_check_mark: Linters are green
 
 ## Required Changes 

- [ ] Check under the review 

 ## Optional suggestions 

-[ ] Check under the review 

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 11:01 UTC, Alfredbis29 commented on README.md
> +- [LIVE-DEMO](https://metrics-webapp-xo2x.onrender.com/)
- [x] Good job of recording the video as required in the previous review but there is still something you need to improve on, your video is less than 5 min, you didn't describe the app functionalities, You didn't  highlight some codes that you are proud of making or you found interested during this project :wink:  kindly fix this as it was required [in the previous review](https://github.com/ritikarawat220/ReactCapstone-project---Metrics-webapp/pull/4#discussion_r1178061706)

2023-04-27 11:01 UTC, Alfredbis29 commented on src/components/Countriesdetail.js
> +    return (
- [ OPTIONAL]When clicking on the arrow left I'm not able to redirect to the home page, kindly fix that when click on the arrow back on the left I should be redirected to the home page again, this will make a good user experience :wink:

2023-04-27 12:53 UTC, levy002 approved these changes
## Hello @ritikarawat220 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Highlights
- Good UI :heavy_check_mark: 
- All suggested changes are implemented :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 12:55 UTC, ritikarawat220 commented
@levy002 Thanks for approving!..
<img src="https://media4.giphy.com/media/KPTnDO32nEHh8ZA5E5/giphy.gif"/>

2023-04-28 07:21 UTC, merged